
# ab做multipart form的POST测试
`ab -v 2 -T "multipart/form-data; boundary=${form_boundary}" -p ~/abpost.txt http://yourhost/upload.php`
需要把post body加到文件中，如：

```shell

form_boundary=-------------------------acebdf13572468

: > post_body
echo -n "--${form_boundary}\r\nContent-Disposition: form-data; name=\"watermark\"; filename=\"f45805bf74a2c55f6233dea7324eca3d.png\"\r\nContent-Type: application/octet-stream\r\n\r\n" >> post_body
cat f45805bf74a2c55f6233dea7324eca3d.png >> post_body

echo -n "\r\n--${form_boundary}\r\nContent-Disposition: form-data; name=\"img\"; filename=\"0222da50ac7f35d3b888b3fb08f331b8.jpg\"\r\nContent-Type: application/octet-stream\r\n\r\n" >> post_body
cat test_pic/0222da50ac7f35d3b888b3fb08f331b8.jpg >> post_body

echo -n "\r\n--${form_boundary}\r\nContent-Disposition: form-data; name=\"alpha\"\r\n\r\n1" >> post_body
echo -n "\r\n--${form_boundary}\r\nContent-Disposition: form-data; name=\"dir\"\r\n\r\n1" >> post_body


echo -n "\r\n--${form_boundary}--\r\n" >> post_body

ab -v 2 -T "multipart/form-data; boundary=${form_boundary}" -p post_body -X 172.16.13.35:8888 http://172.16.13.94:9080/watermark/gen
```

对应的curl命令：
`curl -v -F 'watermark=@f45805bf74a2c55f6233dea7324eca3d.png' -F "img=@test_pic/0222da50ac7f35d3b888b3fb08f331b8.jpg" -F alpha=1 -F dir=1 http://172.16.13.94:9080/watermark/gen`

### 神坑！！！ boundary
body中使用的boundary为 `-{2-}${boundary}`，其中 `${boundary}`表示header中指定的boundary=后面的字符串（`\r\n`之前）；`-{2-}`表示大于或等于两个`-`字符。
啊啊啊啊啊。

# ab/curl使用代理方式
ab： `-X 172.16.13.35:8888`
curl： `-x 172.16.13.35:8888`


# C++中异常处理
```
If it derives from std::exception you can catch by reference:

try
{
    // code that could cause exception
}
catch (const std::exception &exc)
{
    // catch anything thrown within try block that derives from std::exception
    std::cerr << exc.what();
}
But if the exception is some class that has is not derived from std::exception, you will have to know ahead of time it's type (i.e. should you catch std::string or some_library_exception_base).

You can do a catch all:

try
{
}
catch (...)
{
}
but then you can't do anything with the exception.
```
